import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let footer = (<footer>
    <p className='flex justify-center text-sm font-medium text-gray-900 dark:text-white p-4' >Made with 💛</p>
  </footer>)

  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-800`}>
        {children}
        {footer}
      </body>
    </html>
  );
}
