import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let header = (<header>
    <Link href={"/"} className='text-3xl font-bold flex justify-center p-4'>Resume Generator</Link>
  </header>)

  let footer = (<footer>
    <p className='flex justify-center p-4'>Made with 💛</p>
  </footer>)

  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
